"""Shared model presets for EEG-DINO scripts."""

CONFIG = dict(
    n_channels=2,
    sampling_rate=200,
    epoch_duration=30,
    embed_dim=64,
    n_layers=2,
    n_heads=4,
    mlp_dim=128,
    out_dim=4096,
    head_hidden_dim=256,
    head_bottleneck_dim=64,
    n_local_views=8,
    n_masked_views=2,
    batch_size=64,
    learning_rate=1e-4,
    warmup_epochs=10,
    weight_decay_start=0.04,
    weight_decay_end=0.40,
    momentum_start=0.996,
    momentum_end=1.0,
    n_epochs=100,
    mask_strategy='alpha',
)

CONFIG_BCI_2A = dict(
    n_channels=22,
    sampling_rate=250,
    epoch_duration=4,
    embed_dim=128,
    n_layers=4,
    n_heads=8,
    mlp_dim=512,
    out_dim=4096,
    head_hidden_dim=256,
    head_bottleneck_dim=64,
    n_local_views=4,
    n_masked_views=1,
    batch_size=32,
    learning_rate=1.25e-4,
    warmup_epochs=10,
    weight_decay_start=0.04,
    weight_decay_end=0.40,
    momentum_start=0.996,
    momentum_end=1.0,
    n_epochs=100,
    mask_strategy='alpha',
)

CONFIG_BCI_2B = dict(
    n_channels=3,
    sampling_rate=250,
    epoch_duration=6,
    embed_dim=64,
    n_layers=2,
    n_heads=4,
    mlp_dim=128,
    out_dim=4096,
    head_hidden_dim=256,
    head_bottleneck_dim=64,
    n_local_views=4,
    n_masked_views=1,
    batch_size=64,
    learning_rate=1.25e-4,
    warmup_epochs=10,
    weight_decay_start=0.04,
    weight_decay_end=0.40,
    momentum_start=0.996,
    momentum_end=1.0,
    n_epochs=100,
    mask_strategy='spatiotemporal',
)

PRESETS = {
    'tiny': CONFIG,
    'bci_2a': CONFIG_BCI_2A,
    'bci_2b': CONFIG_BCI_2B,
}
